[variables]

NODE_VERSION = "22.14.0"
 
[phases.setup]

nixPkgs = ["nodejs_22"]
 
[phases.install]

cmds = ["npm ci"]
 
[phases.build]

cmds = ["npm run build"]
 
[phases.start]

cmd = "npm run preview -- --host 0.0.0.0 --port $PORT"
 