[variables]
PORT = "80"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "caddy"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.caddy]
nixPkgs = ["caddy"]
cmds = ["caddy fmt --overwrite /assets/Caddyfile"]

[start]
cmd = "exec caddy run --config /assets/Caddyfile --adapter caddyfile 2>&1"
